INSERT INTO `countries` (`id`, `name`, `url_image`, `created_at`) VALUES ('1', 'Guatemala', 'http://aux.iconspalace.com/uploads/1857486532.png', '2019-09-05 00:21:37');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('1', 'Alta Verapaz', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('2', 'Baja Verapaz', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('3', 'Chimaltenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('4', 'Chiquimula', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('5', 'Petén', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('6', 'El Progreso', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('7', 'Quiché', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('8', 'Escuintla', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('9', 'Guatemala', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('10', 'Huehuetenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('11', 'Izabal', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('12', 'Jalapa', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('13', 'Jutiapa', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('14', 'Quetzaltenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('15', 'Retalhuleu', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('16', 'Sacatepéquez', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('17', 'San Marcos', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('18', 'Santa Rosa', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('19', 'Sololá', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('20', 'Suchitepéquez', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('21', 'Totonicapán', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `states` (`id`, `name`, `url_image`, `country_id`) VALUES ('22', 'Zacapa', 'http://aux.iconspalace.com/uploads/1857486532.png', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('1', 'Cobán', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('2', 'San Pedro Carchá', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('3', 'San Juan Chamelco', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('4', 'San Cristóbal Verapaz', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('5', 'Tactic', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('6', 'Tucurú', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('7', 'Panzós', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('8', 'Senahú', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('9', 'Cahabón', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('10', 'Lanquín', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('11', 'Chahal', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('12', 'Fray Bartolomé de las Casas', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('13', 'Chisec', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('14', 'Santa Cruz Verapaz', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('15', 'Santa Catalina La Tinta', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('16', 'Raxruhá', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('17', 'Tamahú', 'https://comidasguatemaltecas.pro/wp-content/uploads/2018/08/Alta-Verapaz-Guatemala.jpg', '1');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('18', 'Cubulco', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('19', 'Santa Cruz el Chol', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('20', 'Granados', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('21', 'Purulhá', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('22', 'Rabinal', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('23', 'Salamá', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('24', 'San Miguel Chicaj', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('25', 'San Jerónimo', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '2');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('26', 'Chimaltenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('27', 'San José Poaquíl', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('28', 'San Martín Jilotepeque', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('29', 'San Juan Comalapa', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('30', 'Santa Apolonia', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('31', 'Tecpán Guatemala', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('32', 'Patzún', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('33', 'Pochuta', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('34', 'Patzicía', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('35', 'Santa Cruz Balanyá', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('36', 'Acatenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('37', 'Yepocapa', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('38', 'San Andrés Itzapa', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('39', 'Parramos', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('40', 'Zaragoza', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('41', 'El Tejar', 'http://aux.iconspalace.com/uploads/1857486532.png', '3');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('42', 'Chiquimula', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('43', 'Camotán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('44', 'Concepción Las Minas', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('45', 'Esquipulas', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('46', 'Ipala', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('47', 'Jocotán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('48', 'Olopa', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('49', 'Quezaltepeque', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('50', 'San José La Arada', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('51', 'San Juan Ermita', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('52', 'San Jacinto', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '4');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('53', 'Dolores', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('54', 'San Benito', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('55', 'Flores', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('56', 'San Francisco', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('57', 'La Libertad', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('58', 'San José', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('59', 'Melchor de Mencos', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('60', 'San Luis', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('61', 'Poptún', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('62', 'Santa Ana', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('63', 'San Andrés', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('64', 'Sayaxché', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '5');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('65', 'Guastatoya', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('66', 'Morazán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('67', 'San Agustín Acasaguastlán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('68', 'San Cristóbal Acasaguastlán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('69', 'El Jícaro', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('70', 'Sansare', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('71', 'Sanarate', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('72', 'San Antonio La Paz', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '6');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('73', 'Santa Cruz del Quiché', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('74', 'Canillá', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('75', 'Chajul', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('76', 'Chicamán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('77', 'Chiché', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('78', 'Chichicastenango', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('79', 'Chinique', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('80', 'Cunén', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('81', 'Ixcán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('82', 'Joyabaj', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('83', 'Nebaj', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('84', 'Pachalum', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('85', 'Patzité', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('86', 'Sacapulas', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('87', 'San Andrés Sajcabajá', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('88', 'San Antonio Ilotenango', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('89', 'San Bartolomé Jocotenango', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('90', 'San Juan Cotzal', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('91', 'San Pedro Jocopilas', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('92', 'Uspantán', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('93', 'Zacualpa', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '7');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('94', 'Escuintla', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('95', 'Guanagazapa', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('96', 'Iztapa', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('97', 'La Democracia', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('98', 'La Gomera', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('99', 'Masagua', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('100', 'Nueva Concepción', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('101', 'Palín', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('102', 'Puerto San José', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('103', 'San Vicente Pacaya', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('104', 'Santa Lucía Cotzumalguapa', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('105', 'Siquinalá', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('106', 'Tiquisate', 'https://visitguatemala.com/descargas/img/mapas/alta-verapaz.jpg', '8');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('107', 'Guatemala', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('108', 'Santa Catarina Pinula', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('109', 'San José Pinula', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('110', 'San José del Golfo', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('111', 'Palencia', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('112', 'Chinautla', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('113', 'San Pedro Ayampuc', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('114', 'Mixco', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('115', 'San Pedro Sacatepéquez', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('116', 'San Juan Sacatepéquez', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('117', 'San Raymundo', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('118', 'Chuarrancho', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('119', 'Fraijanes', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('120', 'Amatitlán', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('121', 'Villa Nueva', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('122', 'Villa Canales', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('123', 'Petapa', 'http://aux.iconspalace.com/uploads/1857486532.png', '9');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('124', 'Aguacatán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('125', 'Chiantla', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('126', 'Colotenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('127', 'Concepción Huista', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('128', 'Cuilco', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('129', 'Huehuetenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('130', 'Jacaltenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('131', 'La Democracia', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('132', 'La Libertad', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('133', 'Tectitán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('134', 'Todos Santos Cuchumatán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('135', 'Unión Cantinil', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('136', 'Malacatancito', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('137', 'Nentón', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('138', 'San Antonio Huista', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('139', 'San Gaspar Ixchil', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('140', 'San Ildefonso Ixtahuacán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('141', 'San Juan Atitán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('142', 'San Juan Ixcoy', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('143', 'San Mateo Ixtatán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('144', 'San Miguel Acatán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('145', 'San Pedro Necta', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('146', 'San Pedro Soloma', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('147', 'San Rafael La Independencia', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('148', 'San Rafael Petzal', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('149', 'San Sebastián Coatán', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('150', 'San Sebastián Huehuetenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('151', 'Santa Ana Huista', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('152', 'Santa Bárbara', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('153', 'Santa Cruz Barillas', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('154', 'Santa Eulalia', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('155', 'Santiago Chimaltenango', 'http://aux.iconspalace.com/uploads/1857486532.png', '10');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('156', 'Puerto Barrios', 'http:', '11');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('157', 'Livingston', 'http:', '11');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('158', 'El Estor', 'http:', '11');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('159', 'Morales', 'http:', '11');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('160', 'Los Amates', 'http:', '11');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('161', 'Jalapa', 'http:', '12');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('162', 'San Pedro Pinula', 'http:', '12');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('163', 'San Luis Jilotepeque', 'http:', '12');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('164', 'San Manuel Chaparrón', 'http:', '12');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('165', 'San Carlos Alzatate', 'http:', '12');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('166', 'Monjas', 'http:', '12');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('167', 'Mataquescuintla', 'http:', '12');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('168', 'Jutiapa', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('169', 'Agua Blanca', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('170', 'Asunción Mita', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('171', 'Atescatempa', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('172', 'Comapa', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('173', 'Conguaco', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('174', 'El Adelanto', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('175', 'El Progreso', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('176', 'Jalpatagua', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('177', 'Jeréz', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('178', 'Moyuta', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('179', 'Pasaco', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('180', 'Quesada', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('181', 'San José Acatempa', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('182', 'Santa Catarina Mita', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('183', 'Yupiltepeque', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('184', 'Zapotitlán', 'http:', '13');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('185', 'Almolonga', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('186', 'Cabricán', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('187', 'Cajolá', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('188', 'Cantel', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('189', 'Coatepeque', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('190', 'Colomba', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('191', 'Concepción Chiquirichapa', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('192', 'El Palmar', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('193', 'Flores Costa Cuca', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('194', 'Génova', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('195', 'Huitán', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('196', 'La Esperanza', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('197', 'Olintepeque', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('198', 'San Juan Ostuncalco', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('199', 'Palestina de Los Altos', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('200', 'Quetzaltenango', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('201', 'Salcajá', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('202', 'San Carlos Sija', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('203', 'San Francisco La Unión', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('204', 'San Martín Sacatepéquez', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('205', 'San Mateo', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('206', 'San Miguel Sigüilá', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('207', 'Sibilia', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('208', 'Zunil', 'http:', '14');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('209', 'Champerico', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('210', 'El Asintal', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('211', 'San Andrés Villa Seca', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('212', 'San Martín Zapotitlán', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('213', 'San Felipe', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('214', 'San Sebastián', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('215', 'Santa Cruz Muluá', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('216', 'Retalhuleu', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('217', 'Nuevo San Carlos', 'http:', '15');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('218', 'Alotenango', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('219', 'Antigua Guatemala', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('220', 'Ciudad Vieja', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('221', 'Jocotenango', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('222', 'Magdalena Milpas Altas', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('223', 'Pastores', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('224', 'San Antonio Aguas Calientes', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('225', 'San Miguel Dueñas', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('226', 'Santa Catarina Barahona', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('227', 'Santa Lucía Milpas Altas', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('228', 'Santa María de Jesús', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('229', 'Santiago Sacatepéquez', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('230', 'Santo Domingo Xenacoj', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('231', 'Sumpango', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('232', 'San Bartolomé Milpas Altas', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('233', 'San Lucas Sacatepéquez', 'http:', '16');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('234', 'San Marcos', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('235', 'Ayutla', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('236', 'Catarina', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('237', 'Comitancillo', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('238', 'Concepción Tutuapa', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('239', 'El Quetzal', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('240', 'El Rodeo', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('241', 'El Tumbador', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('242', 'Ixchiguán', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('243', 'La Reforma', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('244', 'Malacatán', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('245', 'Nuevo Progreso', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('246', 'Ocós', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('247', 'Pajapita', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('248', 'Esquipulas Palo Gordo', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('249', 'San Antonio Sacatepéquez', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('250', 'San Cristóbal Cucho', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('251', 'San José Ojetenam', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('252', 'San Lorenzo', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('253', 'San Miguel Ixtahuacán', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('254', 'San Pablo', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('255', 'San Pedro Sacatepéquez', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('256', 'San Rafaél Pie de La Cuesta', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('257', 'Sibinal', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('258', 'Sipacapa', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('259', 'Tacaná', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('260', 'Tajumulco', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('261', 'Tejutla', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('262', 'Río Blanco', 'http:', '17');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('263', 'Cuilapa', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('264', 'Casillas', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('265', 'Chiquimulilla', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('266', 'Guazacapán', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('267', 'Nueva Santa Rosa', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('268', 'Oratorio', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('269', 'Pueblo Nuevo Viñas', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('270', 'San Juan Tecuaco', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('271', 'San Rafaél Las Flores', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('272', 'Santa Cruz Naranjo', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('273', 'Santa María Ixhuatán', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('274', 'Santa Rosa de Lima', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('275', 'Taxisco', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('276', 'Barberena', 'http:', '18');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('277', 'Sololá', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('278', 'Concepción', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('279', 'Nahualá', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('280', 'Panajachel', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('281', 'San Andrés Semetabaj', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('282', 'San Antonio Palopó', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('283', 'San José Chacayá', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('284', 'San Juan La Laguna', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('285', 'San Lucas Tolimán', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('286', 'San Marcos La Laguna', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('287', 'San Pablo La Laguna', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('288', 'San Pedro La Laguna', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('289', 'Santa Catarina Ixtahuacan', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('290', 'Santa Catarina Palopó', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('291', 'Santa Clara La Laguna', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('292', 'Santa Cruz La Laguna', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('293', 'Santa Lucía Utatlán', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('294', 'Santa María Visitación', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('295', 'Santiago Atitlán', 'http:', '19');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('296', 'Mazatenango', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('297', 'Chicacao', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('298', 'Cuyotenango', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('299', 'Patulul', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('300', 'Pueblo Nuevo', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('301', 'Río Bravo', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('302', 'Samayac', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('303', 'San Antonio Suchitepéquez', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('304', 'San Bernardino', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('305', 'San José El Ídolo', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('306', 'San Francisco Zapotitlán', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('307', 'San Gabriel', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('308', 'San Juan Bautista', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('309', 'San Lorenzo', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('310', 'San Miguel Panán', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('311', 'San Pablo Jocopilas', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('312', 'Santa Barbara', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('313', 'Santo Domingo Suchitepequez', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('314', 'Santo Tomas La Unión', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('315', 'Zunilito', 'http:', '20');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('316', 'Totonicapán', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('317', 'Momostenango', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('318', 'San Andrés Xecul', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('319', 'San Bartolo', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('320', 'San Cristóbal Totonicapán', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('321', 'San Francisco El Alto', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('322', 'Santa Lucía La Reforma', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('323', 'Santa María Chiquimula', 'http:', '21');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('324', 'Cabañas', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('325', 'Estanzuela', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('326', 'Gualán', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('327', 'Huité', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('328', 'La Unión', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('329', 'Río Hondo', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('330', 'San Diego', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('331', 'Teculután', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('332', 'Usumatlán', 'http:', '22');
INSERT INTO `cities` (`id`, `name`, `url_image`, `state_id`) VALUES ('333', 'Zacapa', 'http:', '22');